name: 'Git Next Version'
author: Rick Meneely <rick@meneely.com>
branding:
  icon: chevrons-right
  color: purple
description: Determine the next version based upon last git tag and provided increment
inputs:
  tag_pattern:
    description: The tag pattern to match
    default: 'v[0-9]*.[0-9]*.[0-9]*'
    required: false
  increment:
    description: The semantic version increment - major, minor, patch, none
    default: minor
    required: false
  auto_increment:
    description: Determine the next version based on commit messages
    default: 'false'
    required: false
  auto_increment_major_version_pattern:
    description: The commit message pattern to match major version commits
    default: '^(major|breaking|incompatible):'
    required: false
  auto_increment_minor_version_pattern:
    description: The commit message pattern to match minor version commits
    default: '^(minor|feature):'
    required: false
  auto_increment_limit:
    description: The highest level of auto increment allowed - major, minor, patch
    default: 'minor'
    required: false
  new_prefix:
    description: Sets new prefix for the next version
    default: ''
    required: false
  remove_prefix:
    description: Removes last version prefix for the next version
    default: 'false'
    required: false
  new_suffix:
    description: Sets new suffix for the next version
    default: ''
    required: false
  remove_suffix:
    description: Removes last version suffix for the next version
    default: 'false'
    required: false
  last_version:
    description: Defines the last version instead of searching for it
    default: ''
    required: false
  next_version:
    description: Defines the next version instead of calculating it
    default: ''
    required: false
  set_next_version_tag:
    description: Create a version tag of NEXT_VERSION
    default: 'true'
    required: false
  verbose:
    description: Turns on verbose output
    default: 'false'
    required: false
outputs:
  image:
    description: 'LAST_VERSION=<last version> and NEXT_VERSION=<next version> which can be used to set environment variables'
runs:
  using: docker
  image: Dockerfile
