on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test using ACT
    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          path: 'git-next-version'
      - name: Git Next Version
        uses: rmeneely/git-next-version@v1.0.9
        with:
          last_version: 'v1.0.1'
