on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test using ACT
    steps:
      - name: Git Next Version
        uses: actions/checkout@v2
        with:
          path: "git-next-version"
