on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test using ACT
    steps:
      - name: Git Next Version
        uses: ./ # Uses an action in the root directory
        with:
          last_version: v1.0.0
